import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import TanstackProviders from "@/components/Provider/tanstackproviders";
import Link from "next/link";
// import { BlogProvider } from "./context/BlogsContext";
// import ClientWrapper from "@/lib/client-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div>
          <Link href={"/"} className="pl-5">Home</Link>
          <Link href={"/about"} className="pl-5">About</Link>
          <Link href={"/contact"} className="pl-5">Contact</Link>
          <Link href={"/users"} className="pl-5">Users</Link>
          <Link href={"/blogs"} className="pl-5">Blogs</Link>
          <Link href={"/tanstack"} className="pl-5">Tanstack</Link>
          <Link href={"/providerForm"} className="pl-5">ProviderForm</Link>
          <Link href={"/multiStepForm"} className="pl-5">MultiStepForm</Link>
          <Link href={"/counter"} className="pl-5">Counter</Link>
          <Link href={"/table"} className="pl-5">Tanstack Table</Link>
        </div> */}
        {/* <ClientWrapper>{children}</ClientWrapper> */}
        <div className="bg-blue-50">
          <TanstackProviders>
            {children}
          </TanstackProviders>
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
