import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BlogProvider } from "./context/BlogsContext";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div>
          <Link href={"/"} className="pl-5">Home</Link>
          <Link href={"/about"} className="pl-5">About</Link>
          <Link href={"/contact"} className="pl-5">Contact</Link>
          <Link href={"/users"} className="pl-5">Users</Link>
        </div> */}
        <BlogProvider>
          {children}
        </BlogProvider>
      </body>
    </html>
  );
}
